from tkinter import *

def press(num):
    x=e1.get()
    x=x+str(num)
    e1.delete(0,END)
    e1.insert(0,x)

def c_clear():
    e1.delete(0,END)
    # e1.insert(0,x)

def c_equal():
    x=e1.get()
    x=eval(x)
    e1.delete(0,END)
    e1.insert(0,str(x))
    # e1.config(text=str(x))


root=Tk()
root.geometry("700x400+0+0")
root.title("Calculator")
e1=Entry(root)
b1=Button(root,text="1",height=1, width=7,command=lambda: press(1))
b2=Button(root,text="2",height=1, width=7,command=lambda: press(2))
b3=Button(root,text="3",height=1, width=7,command=lambda: press(3))
b4=Button(root,text="4",height=1, width=7,command=lambda: press(4))
b5=Button(root,text="5",height=1, width=7,command=lambda: press(5))
b6=Button(root,text="6",height=1, width=7,command=lambda: press(6))
b7=Button(root,text="7",height=1, width=7,command=lambda: press(7))
b8=Button(root,text="8",height=1, width=7,command=lambda: press(8))
b9=Button(root,text="9",height=1, width=7,command=lambda: press(9))
b0=Button(root,text="0",height=1, width=7,command=lambda: press(0))
b_plus=Button(root,text="+",height=1, width=7,command=lambda: press("+"))
b_minus=Button(root,text="-",height=1, width=7,command=lambda: press("-"))
b_mul=Button(root,text="*",height=1, width=7,command=lambda: press("*"))
b_div=Button(root,text="/",height=1, width=7,command=lambda: press("/"))
b_clear=Button(root,text="C",height=1, width=7,command=c_clear)
b_equal=Button(root,text="=",height=1, width=7,command=c_equal)

e1.grid(row=0,columnspan=4,ipadx=70)
b1.grid(row=1,column=0)
b2.grid(row=1,column=1)
b3.grid(row=1,column=2)
b_plus.grid(row=1,column=3)
b4.grid(row=2,column=0)
b5.grid(row=2,column=1)
b6.grid(row=2,column=2)
b_minus.grid(row=2,column=3)
b7.grid(row=3,column=0)
b8.grid(row=3,column=1)
b9.grid(row=3,column=2)
b_mul.grid(row=3,column=3)
b0.grid(row=4,column=0)
b_clear.grid(row=4,column=1)
b_equal.grid(row=4,column=2)
b_div.grid(row=4,column=3)
root.mainloop()
